### ISSUE TITLE
Explanations for a couple of red values in Dysentery 0.2.0

### ISSUE THREAD

**Issue by ben-xo** [brunchboy/dysentery#12]
Hi,

I have CDJ-2000 (original, not nexus).

Managed to get a few red values from dysentery, so I thought I would offer an explanation

## 1: large (3-byte) values of pitch2:
![ex1](https://user-images.githubusercontent.com/75862/34456761-68472d78-ed97-11e7-9ce0-0ae29dd4882a.png)
Steps to reproduce:
Wind the jog wheel very fast in vinyl mode.  Maximum value is 7f d7 0a ?

## 2: P1 '???'
![image](https://user-images.githubusercontent.com/75862/34456798-28785e78-ed98-11e7-9764-a8ce45f770b3.png)

This corresponds to 'Cue Listen', i.e. holding down 'Cue' to hear the track from the cue point after the cue point has been set (and the button is lit).

Steps to reproduce:
1 press play
2 press cue
3 press and hold cue again (Cue Listen is for the duration of the press).

**Comment by ben-xo** [comment]
And another: 

## P2 '???' (number 2)

![image](https://user-images.githubusercontent.com/75862/34456896-f5c214c2-ed99-11e7-9b56-b037411c16f5.png)

This value (2) corresponds to rewinding a playing track to the start of the track by pressing track-search-left. It briefly flicks to that value until whilst seeking to the track start.

Steps to reproduce:
1. load a song
2. press play
3. press track search left (or if choosing a track using the scroll wheel in the display, reselect the song that's currently playing)

I would probably call this status 'Loading'

**Comment by brunchboy** [comment]
Hmm, these both seem to be already reflected in the packet analysis document (and therefore Beat Link) but they must not be in dysentery. I’m checking now. But it looks like in both cases you are talking about the field _P1_ (at offset `0x7b`), not _P2_?

**Comment by ben-xo** [comment]
Oh yes. P1, as per screenshot. :)
