### ISSUE TITLE
Is it possible to grab the master output audio stream?

### ISSUE THREAD

**Issue by spmp** [brunchboy/dysentery#13]
Is it possible to grab the master output audio stream to make available as a JACK input for example?

Must the Pioneer gear be on its own private network?

**Comment by brunchboy** [comment]
The audio does not go over the network at all. It is routed by audio cables (digital or analog) between the players and the mixer. The link protocol is for synchronization only.

**Comment by brunchboy** [comment]
As for your question about a private network, no, there is no need for that, although you are going to want to be sure your network has enough free bandwidth for everything you are putting on it.
