### ISSUE TITLE
Support new firmware, bigger status update packets

### ISSUE THREAD

**Issue by brunchboy** [brunchboy/dysentery#2]
Pioneer just released a new firmware version to go along with the NXS2 line; the CDJ status update packets now seem to be 284 bytes long. Need to accommodate this, make room for the additional bytes, and see what else has changed.

**Comment by drummerclint** [comment]
Oh wow.   I wonder how it plays with the older firmware...

Clint

**Comment by brunchboy** [comment]
Hopefully they test with a wide matrix of their own hardware and versions! But sadly they don’t yet test with dysentery and Beat Link Trigger. Anyone have contacts in the company who could help us? 😉

**Comment by brunchboy** [comment]
The changes in 3c0731b seem to be enough to initially support nx2 players. Thanks for the captures and screen shots, @drummerclint!
