### ISSUE TITLE
DJM Packets

### ISSUE THREAD

**Issue by tehcodedninja** [brunchboy/dysentery#4]
What type of data has been identified communicating with DJMs? I am trying to see if mixer fader values are available.

**Comment by brunchboy** [comment]
No, they are not. The mixer sends almost no information at all. The closest you can get to that is the on-air status of the CDJs, which is all-or-nothing depending on the positions of the cross-fader and channel faders, and that only if the feature is enabled on the CDJs.

You can see a complete explanation of all the information that is available in the [Packet Analysis document](https://github.com/brunchboy/dysentery/blob/master/doc/Analysis.pdf).

**Comment by jan2000** [comment]
> which is all-or-nothing depending on the positions of the cross-fader and channel faders

So I am curious, how does the CDJ know that it is on-air? I.e., where is that info in the packets from the DJM?

**Comment by brunchboy** [comment]
That is an interesting question. I’ve not tried looking for that, have you found it yet? It may be in the mixer status packets, or it may be in a private channel that gets set up between the mixer and player directly, so you would need to span a switch port to capture and identify it.

**Comment by jan2000** [comment]
Unfortunately I do not have access to a DJM with link port. Maybe you could provide a capture with known times at which the channel fader is opened and closed?

**Comment by brunchboy** [comment]
I’m sorry, but if I had time to take captures to investigate this, I would simply do it myself. That’s the really tedious part. :) Perhaps someone else with access to the hardware can do it, or perhaps someday I will have the time and get curious.

**Comment by drummerclint** [comment]
I might be able to take a capture this weekend.  What do you want to see specifically?

Clint

On Mar 14, 2018, at 5:51 PM, James Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


I’m sorry, but if I had time to take captures to investigate this, I would simply do it myself. That’s the really tedious part. :) Perhaps someone else with access to the hardware can do it, or perhaps someday I will have the time and get curious.

**Comment by jan2000** [comment]
> I might be able to take a capture this weekend.  What do you want to see specifically?

That would be nice! Could you capture **all** the packets between a DJM and CDJ starting from before they are turned on. Do not load anything, do not play anything. Just turn open the fader, wait some seconds and close the fader making sure the CDJ jog-wheel ring changes from white to red and back. If you could write down the exact times you open and close the fader that would be of great help.

**Comment by jan2000** [comment]
Looking at #7 I figured out the packet for the on-air status. It is very simular to the fader start packet. Sending the following broadcast packet on port 50001 changes the on-air status for the players:

```
51 73 70 74 31 57 6d 4a 4f 4c 03 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 21 00 09 P1 P2 P3 P4 00 00 00 00 00
```

Where Px is:
00 Player x off-air
01 Player x on-air

**Comment by brunchboy** [comment]
Nice work, @jan2000, thank you! I will reopen this issue and try to get both this packet and the fader start packet added to the analysis document.
