### ISSUE TITLE
Last Metadata package

### ISSUE THREAD

**Issue by Chrasonier** [brunchboy/dysentery#6]
Hey,

first I wanna thank you for the great documentation. 
But I have a problem with the the 3rd or 4th track metadata package. I don't get the final answer after last package. Am I right, that the "Seq" have to be 0 0 0 1 and not 1 1 1 1? And that the "Sr" and "rekordbox" field for the queries are the same as in the "Figure 11" paket? 
I choose the playernumber 3, because my virtual player is the number 3, or should I use the number (1 or 2) of my real players?

Br
Tobi

**Comment by brunchboy** [comment]
Hi! Thanks for the kind words. 😄 

It sounds like you are trying to implement a metadata request, and indeed that is quite finicky to get right. Your best bet might be to study a working example. Here is a Java implementation from my beat-link project, the [MetadataFinder](https://github.com/brunchboy/beat-link/blob/master/src/main/java/org/deepsymmetry/beatlink/MetadataFinder.java).

The sequence number `seq` starts out as `0xfffffffe`, then becomes `0x00000000`, `0x00000001`, `0x00000002`, and so on. You need to use the player number of your virtual player in the requests, and your virtual player must already be actively present and visible on the network for the request to work.
